# Generated by Django 5.2.7 on 2025-11-17 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=60, null=True, verbose_name='Sobrenome')),
                ('nick_name', models.CharField(max_length=30, null=True, verbose_name='Apelido')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Numero invalido! Use o Formato +55 (XX) 9XXXX-XXXX', regex='^\\+55\\d{10,11}')], verbose_name='Numero de telefone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
        ),
    ]
