# Generated by Django 5.2.7 on 2025-11-17 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Numero invalido! Use o Formato +55 (XX) 9XXXX-XXXX', regex='^\\+55\\d{10,11}')], verbose_name='Numero de telefone'),
        ),
    ]
