# Generated by Django 5.2.7 on 2026-06-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apelido'),
        ),
    ]
